config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :companies
  devise_for :users
  resources :comments
  get 'pages/info'
  resources :products
  root to: redirect('/products')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    belongs_to :status
    belongs_to :company
    mount_uploader :picture, PictureUploader

    def self.search(search)
        if search
            where(["product_name LIKE ? OR brand LIKE ?","%#{search}%","%#{search}%"])
        else
            all
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:category].blank?
      @products = Product.all.order("created_at DESC")
      @products = Product.search(params[:search])
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(:category_id => @category_id).order("created_at DESC")
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all
    @comment = @product.comments.build
  end

  # GET /products/new
  def new
    @product = current_user.products.build 
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @statuses = Status.all.map{ |c| [c.name, c.id] }
    @companies = Company.all.map{ |c| [c.company_name, c.id] } 
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @statuses = Status.all.map{ |c| [c.name, c.id] }
    @companies = Company.all.map{ |c| [c.company_name, c.id] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)
    # @product.category_id = params[:category_id]
    # @product.status_id = params[:status_id]
    # @product.company_id = params[:company_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        Rails.logger.debug @product.errors.inspect
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = params[:category_id]
    @product.status_id = params[:status_id]
    respond_to do |format|
      
      if @product.update(product_params)
       
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :brand, :picture, :price, :stock, :descrption, :halal_cert, :kkm_cert, :sirim_cert, :category_id, :status_id, :company_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.error_notification %>
  <p>Company: <%= f.collection_select :company_id, current_user.companies, :id, :company_name %> </p></br>
  <%= f.input :product_name %>
  <%= f.input :category_id, collection: @categories %>
  <%= f.input :brand %>
  <%= f.input :status_id, collection: @statuses %>
  <%= f.input :picture %>
  <%= f.input :price %>
  <%= f.input :stock %>
  <%= f.input :descrption %>
  <%= f.submit %>

<% end %>

app/views/products/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-product-form">

    <h1>Editing Product</h1>

      <%= simple_form_for @product do |f| %>
          <p>Company: <%= f.collection_select :company_id, current_user.companies, :id, :company_name %> </p></br>
          <%= f.input :product_name %>
          <%= f.input :category_id, collection: @categories %>
          <%= f.input :brand %>
          <%= f.input :picture %>
          <%= f.input :price %>
          <%= f.input :stock %>
          <%= f.input :descrption %>
          <%= f.input :status_id, collection: @statuses %>
          <%= f.submit %>
        <% end %>
        
      <%= link_to 'Show', @product, class:"btn btn-xs btn-primary" %>
      <%= link_to 'Back', products_path, class:"btn btn-xs btn-success"%>
  </div>
</div>

app/views/products/index.html.erb
<div class="sidenav">
  <% Category.all.each do |category| %>
    <a class="<%= 'active' if params[:category] == category.name %>">
      <%= link_to category.name, products_path(category: category.name)%>
    </a>
  <% end %>
</div>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @products.count == 0 %>
  <h1>There are no product currently in this category</h1>
<% else %> 


  <%= form_tag products_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>
    
    <% @products.each do |product| %>
      <div class="col-md-2">
        <div class="product">
            <a href="/products/<%= product.id %>">
              <%= image_tag product.picture_url(:thumb) if product.picture.present? %>
            </a>
            <h5><%= link_to product.product_name, product %></h5>
            <h5>RM <%= product.price %></h5>
        </div>
      </div>
    <% end %>
<% end %>

app/views/products/new.html.erb
<div class="col-md-6 col-md-offset-3">
    <div class="new-product-form">
        <h1>New Product</h1>

        <%= render 'form', product: @product %>

        <%= link_to 'Back', products_path, class:"btn btn-xs btn-success" %>
    </div>
</div>

app/views/products/show.html.erb
      <div class="row product-show" >
        <div class="col-md-3">
          <%= image_tag(@product.picture_url, :width => 200) if @product.picture.present? %>
        </div>

        <div class="col-md-9">
          <h2><%= @product.product_name %></h2>
          <p><b>Company: </b><%= @product.company.company_name %></p>
          <p><b>Category: </b><%= @product.category.name %></p>
          <p><b>Brand: </b><%= @product.brand %></p>
          <p><b>Price(RM): </b><%= @product.price %></p>
          <p><b>Stock: </b><%= @product.stock %></p>
          <p><b>Description: </b><%= @product.descrption %></p>
          <p><b>Status: </b><%= @product.status.name %></p>

          <% if false %>
            <p><b>Halal Certificate: </b><%= @product.halal_cert %></p>
            <p><b>KKM Certificate: </b><%= @product.kkm_cert %></p>
            <p><b>SIRIM Certificate: </b><%= @product.sirim_cert %></p>
          <% end %>
          
          <% if user_signed_in? %>
            <% if @product.user_id == current_user.id %> 
                <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-xs btn-primary" %>
                <%= link_to 'Destroy', @product, data: { confirm: 'Are you sure?' }, method: :delete, class:"btn btn-xs btn-danger" %>
            <% end %>
          <% end %>
          <%= link_to 'Back', products_path, class:"btn btn-xs btn-success"%>
        </div>
      </div>
  